iris-client-fe/src/App.vue
iris-client-fe/src/components/dashboard/counter-widget.vue
iris-client-fe/src/router/index.ts
iris-client-fe/src/views/home/Home.vue

Index cases views are disabled and not reachable, but "teased":
* Dashboard buttons/links to index cases views are grayed out/disabled
* Access to corresponding views via address bar suppressed by either removing (commenting out) routing links or by redirecting to the dashboard
Refs: iris-connect/iris-backlog#102

feat: disable index cases views

---

iris-client-bff/src/main/java/iris/client_bff/events/EventDataRequestService.java
iris-client-bff/src/main/java/iris/client_bff/events/eps/DataProviderClient.java
iris-client-bff/src/main/java/iris/client_bff/events/eps/DataSubmissionRPCImpl.java
iris-client-bff/src/main/java/iris/client_bff/events/eps/EPSDataProviderClient.java
iris-client-bff/src/main/java/iris/client_bff/proxy/EPSProxyServiceServiceClient.java
iris-client-bff/src/main/java/iris/client_bff/proxy/ProxyServiceClient.java

If a request to get guest list data for an event is aborted, it should be communicated to the provider and attempted submissions to an aborted request have to be ignored (+ the provider should be notified that the submission was not allowed).
This PR implements the above described behaviour.
Refs: iris-connect/iris-backlog#91

feat: aborted requests handling

---

iris-client-bff/pom.xml
iris-client-bff/src/main/java/iris/client_bff/auth/db/DbAuthSecurityAdapter.java
iris-client-bff/src/main/java/iris/client_bff/config/RPCClientConfig.java
iris-client-bff/src/main/java/iris/client_bff/core/health/LocationServiceHealthIndicator.java
iris-client-bff/src/main/resources/application.properties

client via the .../actuator endpoint.
* Only a logged in user with ADMIN role can access the actuator
endpoints.
* Uses the health endpoint of the location service and check its status.
* For a reliable retrieval of the status from the LocationService, a
serializer had to be written to convert an empty parameter array into an
object and a deserializer for the status return object.
Refs  iris-connect/iris-backlog#105

feat: Allows querying system information and the health status of the

---

iris-client-fe/src/views/event-tracking-list/event-tracking-list.view.vue

Refs: iris-connect/iris-backlog#116

bugfix: prevent NPE on events list view when JWT token is expired

---

.prepare-release.sh
.releaserc
iris-client-fe/package-lock.json
iris-client-fe/package.json

The plugin npm-license-crawler caused an error in the build and was
therefore replaced by license-checker.
Refs iris-connect/iris-backlog#107

chore: fixes generation of FOSS license overview with other plugin

---

infrastructure/deployment/.env.sample
infrastructure/deployment/docker-compose-ext-postgres.yml
infrastructure/deployment/docker-compose.yml
infrastructure/deployment/docs/Installation-Standalone.md
iris-client-bff/src/main/resources/application-dev_env.properties
iris-client-bff/src/main/resources/application-docker.properties
iris-client-bff/src/main/resources/application-prod_env.properties
iris-client-bff/src/main/resources/application.properties

* There is a new container in the compose file with shipps all log
messages of the other running containers to log files in the configured
volume folder.
* The folder for the log files is configurable in .env.
* Fixes wrong log level setting: de.healthIMIS is outdated.

chore: describes logging with JARS and add a log shipper to docker-comp.

---

iris-client-fe/src/utils/data-export.ts

I have restored the header mapping function. I had tested it and thought it wasn't needed, but only did so with one case and not all and the one case didn't need it while others did.

fix: SORMAS-compatible CSV-Export of guest lists

---

iris-client-bff/pom.xml

@stefanmichalk 
at the moment the pipeline fails because of a compile error. Reason: Greenmail was only included with maven profile localDev. 
However, I think if Greemail is used within src/main/java we need to always include it in the dependecies.

fix: fixes pipeline build problem

---

iris-client-fe/package.json

Mehrere npm scripte in einem command per Semicolon zu verketten funktioniert leider nur unter Linux basierten Systemen. Windows kann damit nicht umgehen und anscheinend hat auch das .prepare-release.sh script Probleme mit der Ausführung, da die Lizenzdateien seit der Änderung am Code (10. Juni) nicht mehr aktualisiert wurden.
Dieser Pull Request sollte das Problem beheben, wurde aber bisher nur in einer Windows Umgebung getestet.
Wenn möglich bitte unter Linux etc. testen.

fix: fixes license file generation

---

infrastructure/docker/app-eps/conf/roles/prod/app/settings.yml
infrastructure/docker/app-eps/conf/roles/test/app/settings.yml
infrastructure/docker/iris-client-eps/conf/roles/live/hd/001_default.yml
infrastructure/docker/iris-client-eps/conf/roles/staging/hd/001_default.yml
infrastructure/staging/settings/roles/hd-1/settings.yml
infrastructure/stand-alone-deployment/conf/eps/roles/live/hd/001_default.yml
infrastructure/stand-alone-deployment/conf/eps/roles/staging/hd/001_default.yml

Removes stdout channel from eps configs. Could cause problems.

chore: remove stdout from eps config

---

iris-client-fe/src/server/mockAPIServer.ts
iris-client-fe/src/utils/axios.ts
iris-client-fe/src/views/user-login/components/user-login-error.vue
iris-client-fe/src/views/user-login/user-login.view.vue

This pull request fixes the brocken error message handler in the fronend as well (the error message + statusCode from the api are displayed now instead of "undefined (undefined [undefined])". If there is no error message, the fallback "Fehler" is shown.
You can simulate the "username blocked due to too many invalid login attempts" behaviour with the mockApiServer and the following credentials:
- username: admin
- password:
- auth: default / non blocking login error: 401 "Unauthorized"
- block: blocking login error: 401 "User blocked! (dateTime ISOString)"

feat: Shows login rate limit in frontend

---

iris-client-bff/src/main/java/iris/client_bff/config/JsonRpcDataValidator.java
iris-client-bff/src/main/java/iris/client_bff/core/web/dto/Address.java
iris-client-bff/src/main/java/iris/client_bff/events/eps/EventDataControllerImpl.java
iris-client-bff/src/main/java/iris/client_bff/events/web/dto/GuestList.java
iris-client-bff/src/main/java/iris/client_bff/events/web/dto/GuestListDataProvider.java
iris-client-bff/src/test/java/iris/client_bff/events/rpc/EventDataControllerIntegrationTest.java

Example how we can validate data completeness with jax validation and json-rpc. Introduced a new JsonRpcDataValidator that takes care of validating objects and throws a readable exception for json-rpc users. 
Please review and might adapt to other methods and objects.

feat: submitted event data transmitted data are checked for completeness

---

infrastructure/docker/nginx/config/templates/iris-client.conf.template
infrastructure/stand-alone-deployment/conf/nginx/nginx.conf

Refs iris-connect/iris-backlog#168
See https://www.nginx.com/blog/rate-limiting-nginx/ for description of bursts/delay parameters
Limiting API access on an IP basis to 5 requests per second with a burst window of 12 requests.
Frontend assets can be accessed at a higher rate of 15/s and a burst of 25.

feat: enable rate limiting on nginx

---

iris-client-bff/src/main/java/iris/client_bff/users/UserAccountsRepository.java
iris-client-bff/src/main/java/iris/client_bff/users/UserDetailsServiceImpl.java
iris-client-bff/src/main/java/iris/client_bff/users/web/UserController.java
iris-client-bff/src/test/java/iris/client_bff/users/UserControlerTests.java
iris-client-bff/src/test/java/iris/client_bff/users/UserDetailsServiceImplTests.java

* Non admin users can change her/his profile now. Exception is username
and role.
* The PATCH endpoint for update is implemented as patch now. The
validation is also adjusted.
* The last admin can't change her/his role to avoid the lost of all
admins.
* The token will only be invalidated if the username, password or role
has been changed.
* Implements unit tests to check the implementation of the update rules.
* Extends the password validation tests in UserControllerTests to test
behavior on update.
* code cleanup
Refs iris-connect/iris-backlog#237

chore: makes own profile editable for regular users (BFF) and improve the update validation and rules

---

iris-client-bff/src/main/java/iris/client_bff/cases/CaseDataRequestService.java

This is now identical to the behavior for events.
Refs iris-connect/iris-backlog#218

chore: announcement is now aborted when the status is changed

---

iris-client-fe/Dockerfile

This eliminates the current trivy errors.

chore: switch to the official and maintained base image

---

iris-client-bff/pom.xml
iris-client-bff/src/main/java/iris/client_bff/cases/CaseDataRequestRepository.java
iris-client-bff/src/main/java/iris/client_bff/cases/CaseDataSubmissionRepository.java
iris-client-bff/src/main/java/iris/client_bff/cases/CaseDeleteJob.java
iris-client-bff/src/main/java/iris/client_bff/core/IrisDateTimeProvider.java
iris-client-bff/src/main/java/iris/client_bff/events/EventDataRequestRepository.java
iris-client-bff/src/main/java/iris/client_bff/events/EventDataSubmissionRepository.java
iris-client-bff/src/main/java/iris/client_bff/events/EventDeleteJob.java
iris-client-bff/src/main/java/iris/client_bff/events/model/Location.java
iris-client-bff/src/main/resources/application.properties
iris-client-bff/src/test/java/iris/client_bff/FakerConfig.java
iris-client-bff/src/test/java/iris/client_bff/cases/CaseDeleteJobIntegrationTests.java
iris-client-bff/src/test/java/iris/client_bff/core/mail/TestEmailServer.java
iris-client-bff/src/test/java/iris/client_bff/events/EventDeleteJobIntegrationTests.java

* Integrates scheduled jobs which deletes the old cases and events.
* Extends the repositories for the necessary methods.
* Fixes an error in IrisDateTimeProvider. The method is not allowed for
`Instant`.
* Sets the default property values in application.properties.
Integrates JavaFaker library for a simpler and random creation of test
data.
Refs iris-connect/iris-backlog#244

feat: Old cases and events are deleted after a configurable time (default is after 6 months) with all associated data.

---

iris-client-fe/Dockerfile

only needed for the build. This makes it more secure and greatly reduced
in size.
Separates the builder image from the runtime image.

fix: Cleans the Docker image of the frontend from artifacts that are only needed for the build. This makes it more secure and greatly reduced in size.

---

iris-client-bff/src/main/java/iris/client_bff/users/UserAccountsRepository.java
iris-client-bff/src/main/java/iris/client_bff/users/UserDetailsServiceImpl.java
iris-client-bff/src/main/java/iris/client_bff/users/web/UserController.java
iris-client-bff/src/main/java/iris/client_bff/users/web/dto/UserUpdateDTO.java
iris-client-bff/src/main/resources/messages.properties
iris-client-bff/src/main/resources/messages_de.properties
iris-client-bff/src/main/resources/messages_en.properties
iris-client-bff/src/test/java/iris/client_bff/users/UserControllerTests.java
iris-client-bff/src/test/java/iris/client_bff/users/UserDetailsServiceImplTests.java
iris-client-fe/src/api/api.ts
iris-client-fe/src/server/data/dummy-userlist.ts
iris-client-fe/src/server/mockAPIServer.ts
iris-client-fe/src/views/admin-user-edit/admin-user-edit.view.vue
iris-client-fe/tests/e2e/specs/users.js
iris-client-fe/tests/e2e/support/commands.js
iris-client-fe/tests/e2e/support/index.d.ts

If the current user an admin, then the old password is only required if
this user change his own password.
Fixed incorrect comparison of encrypted and unencrypted password.
Refs iris-connect/iris-backlog#250

feat: When a user changes his password, the old password is now also expected and checked to ensure it is correct.

---

.github/workflows/bff_develop.yml
.github/workflows/codeql-analysis.yml
.github/workflows/release-gitflow.yml
.github/workflows/trivy_repo_scan.yml
iris-client-bff/pom.xml
pom.xml

Attention:
Installations with Docker are unaffected because the appropriate Java
version is integrated on the Docker container. Standalone installations
with a separately installed Java need to update it from the update of
IRIS.

feat: Uses and requires Java 17 (new long term support version) as baseline.

---

.github/workflows/fe-e2e-test.yml
.github/workflows/release-gitflow.yml
iris-client-fe/.nvmrc
iris-client-fe/Dockerfile
iris-client-fe/package-lock.json

Note: Version 17 is not supported by the Cypress fail fast module.

chore: update nodejs to version 16

---

iris-client-bff/src/main/resources/db/migration/V1007__readable_token_for_cases.sql
iris-client-bff/src/main/resources/db/migration_mssql/V1007__readable_token_for_cases.sql
iris-client-bff/src/main/resources/db/migration_mysql/V1007__readable_token_for_cases.sql

should not be critical, because feature is not in use yet.

fix: clearing case_data_request before adding new not-null fields.

---

iris-client-fe/src/server/data/data-requests.ts
iris-client-fe/src/utils/data-export/sanitization.ts

First draft for the character extension of the sanitizer.
Should work fine with modern Brothers (IE11 won't work).
Let's discuss it.

fix: extend data export sanitization whitelist to allow any Latin Letter

---

infrastructure/deployment/docker-compose.yml
infrastructure/dev/docker-compose.yml
iris-client-bff/src/main/resources/application-docker.properties
iris-client-bff/src/main/resources/application-prod_db.properties
iris-client-bff/src/main/resources/application-psql_compose_db.properties
iris-client-bff/src/test/java/iris/client_bff/dbms/PostgresIT.java

It turned out that for the update to PostgreSQL 14.x the database files have to be rebuilt. So for now I'm sticking with the last minor version of 13.

feat(Database): Updates the integrated PostgreSQL database (Docker-Compose installation) to the version `13.5`.

---

iris-client-bff/src/main/java/iris/client_bff/auth/db/DbAuthSecurityAdapter.java
iris-client-bff/src/main/java/iris/client_bff/auth/db/IrisAuditorAware.java
iris-client-bff/src/main/java/iris/client_bff/auth/db/JWTAuthorizationFilter.java
iris-client-bff/src/main/java/iris/client_bff/auth/db/UserAccountAuthentication.java
iris-client-bff/src/main/java/iris/client_bff/cases/CaseDataRequest.java
iris-client-bff/src/main/java/iris/client_bff/cases/web/CaseDataRequestController.java
iris-client-bff/src/main/java/iris/client_bff/cases/web/IndexCaseMapper.java
iris-client-bff/src/main/java/iris/client_bff/cases/web/request_dto/IndexCaseDetailsDTO.java
iris-client-bff/src/main/java/iris/client_bff/core/Aggregate.java
iris-client-bff/src/main/java/iris/client_bff/core/Metadata.java
iris-client-bff/src/main/java/iris/client_bff/events/EventDataRequest.java
iris-client-bff/src/main/java/iris/client_bff/events/web/EventDataRequestController.java
iris-client-bff/src/main/java/iris/client_bff/events/web/dto/DataRequestDetails.java
iris-client-bff/src/main/java/iris/client_bff/users/UserAccountsRepository.java
iris-client-bff/src/main/java/iris/client_bff/users/UserDetailsServiceImpl.java
iris-client-bff/src/main/java/iris/client_bff/users/entities/UserAccount.java
iris-client-bff/src/main/java/iris/client_bff/users/web/UserController.java
iris-client-bff/src/main/java/iris/client_bff/users/web/UserMappers.java
iris-client-bff/src/main/java/iris/client_bff/users/web/UserProfileController.java
iris-client-bff/src/main/java/iris/client_bff/users/web/dto/UserDTO.java
iris-client-bff/src/main/resources/db/migration/V1008__add_audit_metadata.sql
iris-client-bff/src/main/resources/db/migration_mssql/V1008__add_audit_metadata.sql
iris-client-bff/src/main/resources/db/migration_mysql/V1008__add_audit_metadata.sql
iris-client-bff/src/test/java/iris/client_bff/cases/web/IndexCaseControllerTest.java
iris-client-bff/src/test/java/iris/client_bff/cases/web/IndexCaseMapperTest.java
iris-client-bff/src/test/java/iris/client_bff/users/UserControllerTests.java
iris-client-bff/src/test/java/iris/client_bff/users/UserDetailsServiceImplTests.java

- Extends database schema and `Metadata` entity basic class for the audit metadata creater and modifier.
- Implements a `AuditorAware` to get the full name of the current user for audit metadata.
- Extends the authentication class `UserAccountAuthentication` to hold more than the user name. This is nessecary to alow the `AuditorAware` implementation to get the full name of the current user.
- Extends the output DTOs `IndexCaseDetailsDTO` and `DataRequestDetails` for creater and modifier.
- Makes `UserAccount` to an aggregate and thus extends it with audit metadata.
- Extends JWTAuthorizationFilter to fill `UserAccountAuthentication` correct.
Refs https://github.com/iris-connect/iris-backlog/issues/204

feat: Extends the audit metadata in BFF to save who create and last modify an entity.
