iris-client-fe/src/components/form/editable-field.vue
iris-client-fe/src/views/event-tracking-details/components/event-tracking-details.component.vue

Please close issue in Backlog after review and merge.

fix iris-connect/iris-backlog#60

---

iris-client-fe/Caddyfile

Since this repo is public and we are about to rollout, this setting can be removed.

Removes HTTP Basic Auth

---

.releaserc

Fixes error: https://github.com/iris-connect/iris-client/actions/runs/876557945

chore: fixes version replacement logic.

---

iris-client-fe/src/components/alerts/alert.component.vue

chore: Removes newline

---

iris-client-bff/src/test/java/iris/client_bff/search_client/web/LocationSearchControllerIntegrationTests.java

Refs iris-connect/iris-backlog#96

fix: adjust unit tests for new location search api

---

infrastructure/staging/settings/roles/private-proxy-eps-1/settings.yml
iris-client-bff/src/main/java/iris/client_bff/events/eps/DataSubmissionRPC.java
iris-client-bff/src/main/java/iris/client_bff/events/eps/DataSubmissionRPCImpl.java

* Corrected typo in settings.yml
* changed parameter name in method submitGuestList from requestId to dataAuthorizationToken

Staging fix

---

infrastructure/deployment/docker-compose-ext-postgres.yml
infrastructure/deployment/docker-compose.yml

This fixes a bug that admin user settings from .env file were not applied correctly.

fix: Admin user settings do not apply

---

iris-client-fe/src/components/form/date-input-field.vue
iris-client-fe/src/components/form/time-input-field.vue

…enable editing of time and date via keyboard after selection via click
Refs: iris-gateway/iris-backlog#83

fix: Improvements to event tracking creation, 

---

.prepare-release.sh

chore: fixes the missing abort if any step of the build script has an error

---

iris-client-fe/src/App.vue

Refs: iris-connect/iris-backlog#122

feat: setting page title globally

---

iris-client-fe/src/components/form/date-input-field.vue
iris-client-fe/src/components/form/time-input-field.vue

Refs: iris-connect/iris-backlog#123

fix: date-picker visual bug when resizing page

---

iris-client-fe/src/views/event-tracking-form/components/location-select-dialog.vue

Corrected PR from base branch devlop.

fix: Handle missing contact property in location object

---

infrastructure/deployment/docs/Installation-Docker-Compose.md
infrastructure/deployment/docs/Installation.md
iris-client-fe/src/server/data/dummy-userlist.ts
iris-client-fe/src/views/admin-user-create/admin-user-create.view.vue
iris-client-fe/src/views/admin-user-edit/admin-user-edit.view.vue
iris-client-fe/src/views/admin-user-list/admin-user-list.view.vue
iris-client-fe/src/views/admin-user-list/components/user-delete-button.vue
iris-client-fe/src/views/user-login/components/user-menu.vue
iris-client-fe/src/views/user-login/user-login.view.vue

I hope I caught all of them.
Gendering is not always easy, but https://geschicktgendern.de helps.

Gendered entries

---

infrastructure/deployment/.env.sample
infrastructure/deployment/docker-compose.yml
infrastructure/deployment/docs/Installation-Docker-Compose.md

feat: Adds possbibility to override standard port for Web Interface

---

infrastructure/deployment/docker-compose-ext-postgres.yml
infrastructure/deployment/docker-compose.yml

Raises the interval for open connections from 5 to 60 s

fix: too many connections from EPS.

---

infrastructure/deployment/docs/Certificate-Process_Prod_technical.md
infrastructure/deployment/scripts/live/create-fingerprint-from-cert.sh

Fixes bugs iris client deployment documentation.

fix broken links in documentation

---

BFF-THIRD-PARTY-LICENSES.md
CHANGELOG.md
iris-client-bff/pom.xml
pom.xml

* date-picker visual bug when resizing page ([#152](https://github.com/iris-connect/iris-client/issues/152)) ([06fbb45](https://github.com/iris-connect/iris-client/commit/06fbb45058e52fba85434ab568432b6133abc477))
* fixes pipeline build problem ([#168](https://github.com/iris-connect/iris-client/issues/168)) ([9a5bd58](https://github.com/iris-connect/iris-client/commit/9a5bd586ac596bf5acaf49451ccab290c87757ed))
* Handle missing contact property in location object, avoid null Error. ([#149](https://github.com/iris-connect/iris-client/issues/149)) ([ce2a686](https://github.com/iris-connect/iris-client/commit/ce2a6862ee9cb7baede0fffcc83db1589e01026a)), closes [iris-gateway/iris-backlog#119](https://github.com/iris-gateway/iris-backlog/issues/119)
* restore the header mapping function …

chore(release): 1.0.0-rc.8 [skip ci]

---

.prepare-release.sh

[fix] Configure (empty) contact data in standalone FE artifact

---

iris-client-fe/README.md
iris-client-fe/src/App.vue
iris-client-fe/src/router/index.ts
iris-client-fe/src/store/store.config.ts
iris-client-fe/src/store/types.ts
iris-client-fe/src/views/home/Home.vue
iris-client-fe/src/views/index-tracking-details/components/index-tracking-submission-url.vue
iris-client-fe/src/views/index-tracking-settings/index-tracking-settings.store.ts

feat: #192 Feature flag for index cases
fix: index-tracking-submission-url: vertical-alignment on firefox + tooltip position

feat: 192 Feature flag for index cases

---

infrastructure/deployment/docker-compose-ext-postgres.yml
infrastructure/deployment/docker-compose.yml

Adds restart policy to all services.

---

infrastructure/staging/docker-compose.yml
iris-client-bff/Readme.md

Enable watchtower for bff+fe on staging/dev environment.

chore: autodeploy to dev/staging server

---

iris-client-fe/package-lock.json
iris-client-fe/package.json
iris-client-fe/src/assets/scss/base/_global.scss

Ticket: https://github.com/iris-connect/iris-backlog/issues/170

npm packages audit

---

iris-client-bff/src/main/java/iris/client_bff/core/utils/ValidationHelper.java
iris-client-bff/src/main/java/iris/client_bff/events/eps/EventDataControllerImpl.java

Input validation for guest lists from app providers:
- No format assumptions
- Strings are cutted at max length of DB field
- Attack detection validation for Strings
- New forbidden keyword 
Tested with "naughty" guestlist

fix: bl 233 guestlist validation

---

iris-client-bff/src/main/java/iris/client_bff/cases/CaseDataSubmissionService.java
iris-client-bff/src/main/java/iris/client_bff/events/EventDataSubmissionService.java

Refs  iris-connect/iris-backlog#203

chore: alert is sent when Data-Authorization-Token is not found for a data delivery

---

iris-client-fe/src/views/admin-user-list/admin-user-list.view.vue
iris-client-fe/src/views/user-login/user-login.store.ts

feat: disables the user delete button for the current user

---

iris-client-bff/src/main/java/iris/client_bff/auth/db/DbAuthProperties.java
iris-client-bff/src/main/java/iris/client_bff/auth/db/InitialAdminLoader.java
iris-client-bff/src/main/java/iris/client_bff/auth/db/login_attempts/LoginAttemptsProperties.java
iris-client-bff/src/main/resources/application-prod_auth.properties
iris-client-bff/src/test/java/iris/client_bff/auth/db/InitialAdminLoaderTest.java

Adapts code of InitialAdminLoader and his test to the new requirements.
Improves other propertie validation too.
Refs iris-connect/iris-backlog#223

fix: Removes default admin credentials for production environment and prevents the application from starting if these properties are missing.

---

iris-client-bff/src/main/java/iris/client_bff/users/UserDetailsServiceImpl.java
iris-client-bff/src/main/java/iris/client_bff/users/web/UserController.java

feat: Blocks delete requests in the client backend if a user would delete himself.

---

infrastructure/deployment/docker-compose-ext-postgres.yml
infrastructure/deployment/docker-compose.yml

The URL for digitales Wartezimmer can now be configured. It defaults to the production URL.

Adds config option for DW url. 

---

infrastructure/dev/.env
infrastructure/dev/settings/roles/private-proxy-1/settings.yml
infrastructure/docker/app-eps/Dockerfile
infrastructure/docker/iris-client-eps/Dockerfile
infrastructure/docker/iris-client-proxy/Dockerfile
infrastructure/docker/iris-client-proxy/conf/roles/live/private-proxy/001_default.yml
infrastructure/docker/iris-client-proxy/conf/roles/staging/private-proxy/001_default.yml
infrastructure/stand-alone-deployment/conf/proxy/roles/live/private-proxy/001_default.yml
infrastructure/stand-alone-deployment/conf/proxy/roles/staging/private-proxy/001_default.yml

feat: update eps to 0.1.61 and adjust config for new eps version

---

iris-client-bff/src/main/java/iris/client_bff/core/utils/ValidationHelper.java
iris-client-bff/src/test/java/iris/client_bff/users/UserControlerTests.java
iris-client-fe/src/config.ts

Refs iris-connect/iris-backlog#222

chore: adapts the password RegEx to the final version

---

infrastructure/deployment/docs/Installation-Docker-Compose.md
infrastructure/deployment/docs/Installation.md
infrastructure/deployment/docs/Upgrade-Guides.md
infrastructure/stand-alone-deployment/README.md

Latest docs for major release.

Update doc for major release

---

iris-client-fe/src/views/iris-message-create/iris-message-create.view.vue

feat: add hint to search for hd-contacts by postal code or city

---

iris-client-bff/src/main/java/iris/client_bff/config/HibernateSearchConfig.java
iris-client-bff/src/main/java/iris/client_bff/core/model/Address.java
iris-client-bff/src/main/java/iris/client_bff/core/validation/NoSignOfAttack.java
iris-client-bff/src/main/java/iris/client_bff/vaccination_info/VaccinationInfo.java
iris-client-bff/src/main/java/iris/client_bff/vaccination_info/VaccinationInfoService.java
iris-client-bff/src/main/java/iris/client_bff/vaccination_info/eps/VaccinationInfoController.java
iris-client-bff/src/main/java/iris/client_bff/vaccination_info/web/VaccinationInfoController.java
iris-client-bff/src/test/java/iris/client_bff/vaccination_info/VaccinationInfoDataInitializer.java
iris-client-bff/src/test/java/iris/client_bff/vaccination_info/eps/VaccinationInfoControllerImplIntegrationTests.java
iris-client-bff/src/test/java/iris/client_bff/vaccination_info/web/VaccinationInfoControllerIntegrationTest.java

- Implements an endpoint for a pageable list of vaccination reports as overview.
- Implements an endpoint for a details view of one vaccination report.
Refs https://github.com/iris-connect/iris-backlog/issues/275

chore(vaccination report): implements the REST API for vaccination report FE
